export const LOGOUT_REASONS = Object.freeze({
  USER_LOGOUT: 'USER_LOGOUT',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  PORTAL_REAUTH_FAILED: 'PORTAL_REAUTH_FAILED',
  STORAGE_CORRUPT: 'STORAGE_CORRUPT',
});

