export const basePalette = {
  brand: {
    primary: '#FF7A00',
    primaryPressed: '#E96A00',
    primarySoft: '#FFF1E6',
  },
  neutral: {
    900: '#0B0F14',
    800: '#111827',
    700: '#334155',
    600: '#475569',
    500: '#64748B',
    200: '#E5E7EB',
    100: '#F3F4F6',
  },
  surface: {
    light: '#FFFFFF',
    dark: '#111827',
  },
  background: {
    light: '#FAF7F2',
    dark: '#0B0F14',
  },
  text: {
    primaryLight: '#101828',
    secondaryLight: '#667085',
    primaryDark: '#F8FAFC',
    secondaryDark: '#94A3B8',
  },
  status: {
    success: '#22C55E',
    error: '#EF4444',
    warning: '#F59E0B',
    info: '#3B82F6',
  },
};

export const theme = {
  light: {
    mode: 'light',
    colors: {
      background: basePalette.background.light,
      surface: basePalette.surface.light,
      surfaceElevated: basePalette.neutral[100],
      border: basePalette.neutral[200],
      textPrimary: basePalette.text.primaryLight,
      textSecondary: basePalette.text.secondaryLight,
      textMuted: basePalette.neutral[500],
      overlay: 'rgba(11, 15, 20, 0.4)',
      primary: basePalette.brand.primary,
      primaryPressed: basePalette.brand.primaryPressed,
      primarySoft: basePalette.brand.primarySoft,
      accent: basePalette.brand.primary,
      accentStrong: basePalette.brand.primaryPressed,
      accentSoft: basePalette.brand.primarySoft,
      accentOrange: basePalette.brand.primary,
      accentOrangeSoft: basePalette.brand.primarySoft,
      success: basePalette.status.success,
      warning: basePalette.status.warning,
      error: basePalette.status.error,
      danger: basePalette.status.error,
      info: basePalette.status.info,
      white: '#FFFFFF',
      black: '#000000',
    },
  },
  dark: {
    mode: 'dark',
    colors: {
      background: basePalette.background.dark,
      surface: basePalette.surface.dark,
      surfaceElevated: basePalette.neutral[800],
      border: basePalette.neutral[700],
      textPrimary: basePalette.text.primaryDark,
      textSecondary: basePalette.text.secondaryDark,
      textMuted: basePalette.neutral[500],
      overlay: 'rgba(11, 15, 20, 0.65)',
      primary: basePalette.brand.primary,
      primaryPressed: basePalette.brand.primaryPressed,
      primarySoft: '#3B2615',
      accent: basePalette.brand.primary,
      accentStrong: basePalette.brand.primaryPressed,
      accentSoft: '#3B2615',
      accentOrange: basePalette.brand.primary,
      accentOrangeSoft: '#3B2615',
      success: basePalette.status.success,
      warning: basePalette.status.warning,
      error: basePalette.status.error,
      danger: basePalette.status.error,
      info: basePalette.status.info,
      white: '#FFFFFF',
      black: '#000000',
    },
  },
};

export const getTheme = (mode = 'light') => theme[mode] || theme.light;
